<?php

namespace Swoole\Thrift;

use Thrift;
use Thrift\Server\TSimpleServer;
use Swoole\Core\Di;

class Server extends TSimpleServer
{
    /**
     * Global RPC Processor Instance.
     *
     * @var class generated by thrift auto-generation
     */
    protected $processor = null;

    public function onReceive($serv, $fd, $from_id, $data)
    {
        $config = Di::get('config');
        $processor_class = $config['processor'];
        $handler_class = $config['handler'];

        $handler = new $handler_class();
        $this->processor = new $processor_class($handler);

        $socket = new Socket();
        $socket->setHandle($fd);
        $socket->buffer = $data;
        $socket->server = $serv;
        $protocol = new Thrift\Protocol\TBinaryProtocol($socket, false, false);

        try {
            $protocol->fname = $config['name'];
            $this->processor->process($protocol, $protocol);
        } catch (\Exception $e) {
        }
    }
}
